# Generated by Django 4.0.3 on 2022-04-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogtest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='obesity_rate',
            new_name='accuracy',
        ),
    ]
